baseURL = "http://dev.followmystomach.com/"
languageCode = "en-us"
title = "Follow My Stomach"
theme = "hugo-coder"

[params]
    since = 2019

[languages]
    [languages.en]
        languagename = "English"
        
        [languages.en.menu]
            [[languages.en.menu.main]]
            name = "Meal Plans"
            weight = 1
            url = "meal-plans/"

            [[languages.en.menu.main]]
            name = "Travel"
            weight = 2
            url = "travel/"

            [[languages.en.menu.main]]
            name = "Skills"
            weight = 3
            url = "skills/"

            [[languages.en.menu.main]]
            name = "About"
            weight = 4
            url = "about/"