baseURL = "http://dev.followmystomach.com/"
languageCode = "en-us"
title = "Follow My Stomach"
theme = "hugo-coder"

[params]
    since = 2019

[languages]
    [languages.en]
        languagename = "English"
        
        [languages.en.menu]
            [[languages.en.menu.main]]
            name = "Meals"
            weight = 1
            url = "meals/"

            [[languages.en.menu.main]]
            name = "Travel"
            weight = 2
            url = "travel/"

            [[languages.en.menu.main]]
            name = "Leftovers"
            weight = 2
            url = "leftovers/"
            
            [[languages.en.menu.main]]
            name = "Skills"
            weight = 3
            url = "skills/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true

